### ISSUE TITLE
wm-metrics fdc-report crashes when used on a category with a quote

### ISSUE THREAD

**Issue by JeanFred** [Commonists/wm_metrics#21]
Steps to reproduce:
- Got to https://tools.wmflabs.org/wm-metrics/fdc
- Enter 110 ans d'automobile au Grand Palais - Supported by Wikimedia France
- Error 400

When checking the logs:
```
2015-04-20 20:55:50: Exception on /fdc/submit [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/project/wm-metrics/wm_metrics/app/wmmetrics.py", line 61, in compute_fdc_report
    pixel_count_on=pixel_count_on)
  File "/data/project/wm-metrics/wm_metrics/app/../wm_metrics/wmfr_photography.py", line 65, in make_example_report
    nb_files = metrics.nb_files_indicator("nb")
  File "/data/project/wm-metrics/wm_metrics/app/../wm_metrics/commons_cat_metrics.py", line 62, in nb_files_indicator
    self.nb_files = [self.quarters[i].get_nb_files() for i in range(4)]
  File "/data/project/wm-metrics/wm_metrics/app/../wm_metrics/commons_cat_metrics.py", line 232, in get_nb_files
    self.cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'automobile_au_Grand_Palais_-_Supported_by_Wikimedia_France'\n    AND IF(oldimage.' at line 7")
```

It appears the quote is not properly escaped.

**Comment by JeanFred** [comment]
I believe this is now fixed.
